/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    static String getDatabaseFileName(String[] args) {
        String databaseFileName = "test";

        for (int i = 0; i < args.length; i++) {
            String arg = args[i];
            if ("-databaseFileName".equals(arg) && i + 1 < args.length) {
                databaseFileName = args[i + 1];
                break;
            }
        }
        return databaseFileName;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String databaseFileName = getDatabaseFileName(args);

        H2ConnectionTest db = new H2ConnectionTest(databaseFileName);
        db.createTable();

        TextUI ui = new TextUI();
    }
}
